version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: hotel_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  app:
    container_name: hotel_booking_api
    image: chazari/hotel_booking_api:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hotel_booking
      - PORT=3000
      - CLIENTS_API_URL=http://localhost:3000/clients
    depends_on:
      - db

volumes:
  db_data:
